[package]
name = "hir"
version = "0.1.0"
edition = "2024"

[dependencies]
ast  = { path = "../ast" }
syntax = { path = "../syntax" }


la-arena = "0.3.1"
miette = { version = "7.5.0", features = ["fancy"] }
smol_str = "0.3.2"
thiserror = "2.0.11"


[dev-dependencies]
parser = { path = "../parser" }