name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  RUSTFLAGS: -C strip=symbols
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"
  SCCACHE_CACHE_SIZE: "25GB"
  CARGO_TERM_COLOR: always
  WASM_BUILD_CLEAN_TARGET: 1

jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Sccache
      uses: mozilla-actions/sccache-action@v3.4.0

    - name: Install stable Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
        override: true
        
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose --release

    - name: Run fmt
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy --release --locked --all-targets -- -D warnings 
  
  coverage:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Run Sccache
        uses: mozilla-actions/sccache-action@v0.0.4
      
      - name: Install Rust
        run: rustup update stable
        
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
        
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 
          files: lcov.info
          fail_ci_if_error: true
