name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  RUSTFLAGS: -C strip=symbols
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"
  SCCACHE_CACHE_SIZE: "50GB"
  CARGO_TERM_COLOR: always
  WASM_BUILD_CLEAN_TARGET: 1

jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: sccache
      uses: mozilla-actions/sccache-action@v0.0.4

    - name: stable toolchain
      # uses: actions-rust-lang/setup-rust-toolchain@v1
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
        override: true
        
    - name: build
      run: cargo build --verbose

    - name: run tests
      run: cargo test --verbose --release

    - name: format
      run: cargo fmt --all -- --check

    - name: clippy
      run: cargo clippy --release --locked --all-targets -- -D warnings 
  
  coverage:
    # permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: sccache
      uses: mozilla-actions/sccache-action@v0.0.4

    - name: stable toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
        
    # - name: install tarpaulin
    #   run: cargo install cargo-tarpaulin
      
    # - name: rust-tarpaulin
      # run: cargo tarpaulin --release --all-features --line --count --tests --verbose --color Always
    #   uses: actions-rs/tarpaulin@v0.1.0
    #   with:
    #       token: ${{ secrets.GITHUB_TOKEN }}

    - name: run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.32.0'
        args: '-- --test-threads 1 --release --all-features --line --count --tests --verbose --color Always'
